@startuml context
title Диаграмма контекста TOBE 1Y

!include C4_Templates/C4_Container.puml

Person(HouseOwner, "Владелец дома")
Person(Support, "Техническая поддержка")

System(WebApp, "Web/Mobile App", "Входная точка управления умного дома")
System(TechSupportSystem, "Обработка инцидентов", "Ошибки оборудования, ПО, консультации по самостоятельному подключению")
System(CommunicationSystem, "Отправка оповещений", "Единая точка для обработки очереди на коммуникацию с пользователем")

System_Boundary(EcosystemRemoteBackend, "Smart Home Core") {
    Container(DeviceManagement, "Управленим устройствами", "Формирует команды для устройств со стороны удаленного сервера")
    Container(UseCaseManagement, "Управленим сценариями", "Формирует команды для сценария, проверяет факт выполнения, управляет расписанием")
    Container(Telemetry, "Телеметрия/Мониторинг", "Собирает значения с датчиков и группирует")
}

Boundary(LocalNetwork, "Локальная сеть/умный дом") {
    System_Ext(SmartDevice, "Умное устройство X", "Батарея, лампочка, камера, замок, вал, etc.")
    System_Ext(SmartMeasure, "Умный датчик X", "Датчик температуры, света, движения, закрытия дверей, etc. ")
    Container(SmartHub, "Device Hub", "Управляет устройствами и собирает метрики в локальной сети умного дома")
    Container(DeviceDiscovery, "Обнаружение устройств", "Автоматически обнаруживает устройство/датчик при подключении WiFi")
}

Rel(WebApp, TechSupportSystem, "Заводит инцидент", "REST/HTTPS")
Rel(Support, TechSupportSystem, "Обрабатывает инцидент", "REST/HTTPS")

Rel(HouseOwner, WebApp, "Заходит на сайт/в приложение", "REST/HTTPS")
Rel(WebApp, DeviceManagement, "Отправляет сигнал для устройства")
Rel(WebApp, Telemetry, "Получает агрегат по значениям датчиков", "REST/HTTPS")
Rel(WebApp, UseCaseManagement, "Настраивает сценарий", "REST/HTTPS")

Rel(UseCaseManagement, DeviceManagement, "Отправляет последовательность команд для выпонения сценария", "REST/HTTPS")
Rel(UseCaseManagement, Telemetry, "Получает агрегаты по датчикам", "REST/HTTPS")

Rel(DeviceDiscovery, SmartDevice, "Обнаруживает устройство", "ZigBee")
Rel(DeviceDiscovery, SmartMeasure, "Обнаруживает датчик", "ZigBee")

Rel(DeviceManagement, SmartHub, "Отправляет управляющий сигнал", "REST/HTTPS")
Rel(SmartHub, SmartDevice, "Отправляет управляющий сигнал", "REST/HTTPS")
Rel(SmartMeasure, SmartHub, "Отправляет данные измерений", "ZigBee")
Rel(SmartHub, Telemetry, "Отправляет данные измерений", "TCP/KAFKA")

Rel(DeviceDiscovery, DeviceManagement, "Событие о новом устройстве", "TCP/KAFKA")
Rel(DeviceDiscovery, Telemetry, "Событие о новом датчике", "TCP/KAFKA")

Rel(SmartDevice, SmartMeasure, "Получает актуальные данные об измерениях", "ZigBee")
Rel(Telemetry, CommunicationSystem, "Отправляет события о сбоях в очередь на коммуникацию", "TCP/KAFKA")
Rel(TechSupportSystem, CommunicationSystem, "Отправляет статусы инцидентов", "TCP/KAFKA")
Rel(CommunicationSystem, HouseOwner, "Оповещает", "PUSH, SMS, CALL")

@enduml